OLSRD_SOURCES = src/builddata.c \
	src/hashing.c \
	src/duplicate_handler.c \
	src/lq_plugin_default_float.c \
	src/lq_packet.c \
	src/plugin_util.c \
	src/packet.c \
	src/hna_set.c \
	src/duplicate_set.c \
	src/mpr_selector_set.c \
	src/generate_msg.c \
	src/fpm.c \
	src/parser.c \
	src/process_package.c \
	src/mpr.c \
	src/scheduler.c \
	src/olsr_cookie.c \
	src/ipcalc.c \
	src/neighbor_table.c \
	src/lq_plugin_default_ffeth.c \
	src/lq_plugin_default_ff.c \
	src/lq_plugin.c \
	src/olsr_switch/ohs_cmd.c \
	src/olsr_switch/link_rules.c \
	src/olsr_switch/main.c \
	src/net_olsr.c \
	src/mantissa.c \
	src/olsr.c \
	src/interfaces.c \
	src/link_set.c \
	src/cfgparser/olsrd_conf.c \
	src/cfgparser/oparse.c \
	src/cfgparser/cfgfile_gen.c \
	src/cfgparser/oscan.c \
	src/common/autobuf.c \
	src/common/avl.c \
	src/common/list.c \
	src/build_msg.c \
	src/olsr_niit.c \
	src/process_routes.c \
	src/lq_mpr.c \
	src/ipc_frontend.c \
	src/gateway_default_handler.c \
	src/olsr_spf.c \
	src/mid_set.c \
	src/main.c \
	src/routing_table.c \
	src/rebuild_packet.c \
	src/two_hop_neighbor_table.c \
	src/unix/ifnet.c \
	src/unix/misc.c \
	src/unix/log.c \
	src/tc_set.c \
	src/hysteresis.c \
	src/linux/net.c \
	src/linux/kernel_routes_nl.c \
	src/linux/lq_plugin_ffeth_nl80211.c \
	src/linux/apm.c \
	src/linux/nl80211_link_info.c \
	src/linux/kernel_tunnel.c \
	src/gateway.c \
	src/lq_plugin_default_fpm.c \
	src/plugin_loader.c
